"""Numerical equivariance test for the tetrahedral (T) candidate family.

This is the mathematical gate for the first polyhedral specimen of the symmetry
program. Unlike the C_n / S4 families (which act on the plane w = x+iy with z a
separate height), the polyhedral families act on all of R^3 at once, and the
group acts **irreducibly**: the only linear map commuting with T is a scalar, so
there is no saddle-focus linear engine -- all of the chaos must come from the
nonlinear (equivariant) terms, and the rotation enters only through the cross
term. This test pins down that the candidate flow is equivariant under the
tetrahedral rotation group T (order 12), and *only* that group within the
relevant lattice: NOT the larger octahedral group O (order 24), and NOT the
full tetrahedral group with reflections T_h (the flow must be chiral / proper).

The group T = A4 is generated by

    sigma3: (x, y, z) -> (y, z, x)     3-fold rotation about the body diagonal (1,1,1)
    sigma2: (x, y, z) -> (x, -y, -z)   2-fold rotation about the x-axis

Its lowest non-trivial invariant is I_T = x*y*z (degree 3), invariant under T but
**anti-invariant** under the octahedral 4-fold c4z: (x,y,z) -> (-y, x, z), where
xyz -> -xyz. That anti-invariance is exactly what makes grad(I_T) = (yz, zx, xy)
(and the cross term X x grad(I_T)) break O while preserving T -- the T-signature.

Because sigma3, sigma2, c4z are proper rotations, a flow ds/dt = F(s) is
g-equivariant iff F(g.s) = g.F(s).
"""

from __future__ import annotations

import numpy as np
import pytest

from atlas.family_t import N_PARAMS, PARAM_HI, PARAM_LO, velocity

TOL = 1e-12

# --- The group, defined here as the authoritative spec the module must satisfy.
SIGMA3 = np.array([[0.0, 1.0, 0.0], [0.0, 0.0, 1.0], [1.0, 0.0, 0.0]])  # (x,y,z)->(y,z,x)
SIGMA2 = np.array([[1.0, 0.0, 0.0], [0.0, -1.0, 0.0], [0.0, 0.0, -1.0]])  # (x,y,z)->(x,-y,-z)
C4Z = np.array([[0.0, -1.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, 1.0]])  # (x,y,z)->(-y,x,z) in O\T
INV = -np.eye(3)  # inversion: in T_h \ T


def _close_group(generators, tol=1e-9, cap=10_000):
    """Closure of a set of matrices under multiplication (the generated group)."""
    elems = [np.eye(3)]

    def known(M):
        return any(np.allclose(M, E, atol=tol) for E in elems)

    frontier = [np.eye(3)] + [np.array(g) for g in generators]
    for g in generators:
        if not known(g):
            elems.append(np.array(g))
    changed = True
    while changed and len(elems) < cap:
        changed = False
        for A in list(elems):
            for g in generators:
                M = A @ g
                if not known(M):
                    elems.append(M)
                    changed = True
    return elems


def _random_states_and_params(rng, count):
    states = [rng.uniform(-2.0, 2.0, 3) for _ in range(count)]
    params = [rng.uniform(PARAM_LO, PARAM_HI) for _ in range(count)]
    return states, params


def test_param_box_shapes_are_consistent():
    assert PARAM_LO.shape == (N_PARAMS,)
    assert PARAM_HI.shape == (N_PARAMS,)
    assert np.all(PARAM_HI > PARAM_LO)


def test_generators_are_proper_rotations():
    for M in (SIGMA3, SIGMA2, C4Z):
        assert np.allclose(M @ M.T, np.eye(3), atol=TOL)
        assert np.linalg.det(M) == pytest.approx(1.0, abs=1e-12)


def test_generated_group_has_order_12():
    """sigma3 (order 3) and sigma2 (order 2) generate the order-12 group T = A4."""
    G = _close_group([SIGMA3, SIGMA2])
    assert len(G) == 12
    # T is a proper subgroup of O: adding c4z must enlarge it to order 24.
    GO = _close_group([SIGMA3, SIGMA2, C4Z])
    assert len(GO) == 24


def test_flow_is_T_equivariant_under_full_group():
    """F(g.X) == g.F(X) to machine precision for every element of T, random params."""
    G = _close_group([SIGMA3, SIGMA2])
    rng = np.random.default_rng(20260611)
    states, params = _random_states_and_params(rng, 60)
    for X, p in zip(states, params):
        FX = velocity(X, p)
        for g in G:
            assert np.allclose(velocity(g @ X, p), g @ FX, atol=TOL, rtol=0)


def test_flow_is_NOT_O_equivariant():
    """The grad(xyz) / cross terms are anti-equivariant under c4z, breaking O.

    If the flow were O-equivariant the attractor's symmetry group would be the
    larger octahedral group and the tetrahedral novelty claim would collapse.
    """
    rng = np.random.default_rng(101)
    states, params = _random_states_and_params(rng, 50)
    violations = 0
    for X, p in zip(states, params):
        if not np.allclose(velocity(C4Z @ X, p), C4Z @ velocity(X, p), atol=1e-9):
            violations += 1
    assert violations == len(states)


def test_flow_is_NOT_inversion_equivariant():
    """The flow must be chiral: not symmetric under inversion (excludes T_h).

    grad(xyz) is even under X -> -X while a proper equivariant must be odd, so
    the a-term breaks inversion and the attractor carries only the proper group T.
    """
    rng = np.random.default_rng(202)
    states, params = _random_states_and_params(rng, 50)
    violations = 0
    for X, p in zip(states, params):
        if not np.allclose(velocity(INV @ X, p), INV @ velocity(X, p), atol=1e-9):
            violations += 1
    assert violations == len(states)


def test_nonlinear_terms_are_load_bearing():
    """Zeroing both nonlinear coefficients (a, b) restores full O(3) symmetry.

    With a = b = 0 only the radial scalar term (rho - d*r^2) X remains, which is
    equivariant under every orthogonal map -- in particular c4z, so O is restored
    (indeed the flow becomes SO(3)-symmetric and integrable). With either
    nonlinear term present, O is broken. This pins the novelty boundary at T (not
    O) and guards against silently dropping the symmetry-reducing terms.
    """
    from atlas.family_t import param_names

    names = param_names()
    assert "a" in names and "b" in names
    ai, bi = names.index("a"), names.index("b")

    rng = np.random.default_rng(303)
    states, params = _random_states_and_params(rng, 40)
    for X, p in zip(states, params):
        p = np.array(p, dtype=float)
        # Nonlinear terms present -> O broken.
        assert not np.allclose(velocity(C4Z @ X, p), C4Z @ velocity(X, p), atol=1e-9)
        # Kill both nonlinear terms -> O (and inversion, and all of O(3)) restored.
        p[ai] = 0.0
        p[bi] = 0.0
        assert np.allclose(velocity(C4Z @ X, p), C4Z @ velocity(X, p), atol=1e-11)
        assert np.allclose(velocity(INV @ X, p), INV @ velocity(X, p), atol=1e-11)
