"""Numerical equivariance test for the octahedral (O) candidate family.

Pins down that the candidate flow is equivariant under the octahedral rotation
group O (order 24, the rotation group of the cube/octahedron) and only that group
within the relevant lattice: it is genuinely larger than the tetrahedral group T
(the a-term (x^3,y^3,z^3) is O-invariant where T's xyz is not), it is NOT the full
O_h with reflections (the cross term breaks inversion -> the attractor is chiral),
and it is NOT all of SO(3) (the nonlinear terms are anisotropic).

O is generated by

    c4z:    (x, y, z) -> (-y, x, z)     4-fold rotation about z
    sigma3: (x, y, z) -> (y, z, x)      3-fold rotation about the body diagonal

and contains T as an index-2 subgroup. Lowest invariant beyond r^2 is the quartic
J = x^4 + y^4 + z^4. Because c4z, sigma3 are proper rotations, equivariance means
F(g.s) = g.F(s).
"""

from __future__ import annotations

import numpy as np
import pytest

from atlas.family_o import N_PARAMS, PARAM_HI, PARAM_LO, velocity

TOL = 1e-12

C4Z = np.array([[0.0, -1.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, 1.0]])  # (x,y,z)->(-y,x,z)
SIGMA3 = np.array([[0.0, 1.0, 0.0], [0.0, 0.0, 1.0], [1.0, 0.0, 0.0]])  # (x,y,z)->(y,z,x)
INV = -np.eye(3)


def _close_group(generators, tol=1e-9):
    elems = [np.eye(3)]

    def known(M):
        return any(np.allclose(M, E, atol=tol) for E in elems)

    for g in generators:
        if not known(g):
            elems.append(np.array(g))
    changed = True
    while changed:
        changed = False
        for A in list(elems):
            for g in generators:
                M = A @ g
                if not known(M):
                    elems.append(M)
                    changed = True
    return elems


def _rand_rotation(rng):
    A = rng.normal(size=(3, 3))
    Q, R = np.linalg.qr(A)
    Q = Q @ np.diag(np.sign(np.diag(R)))
    if np.linalg.det(Q) < 0:
        Q[:, 0] = -Q[:, 0]
    return Q


def _states_params(rng, count):
    return [rng.uniform(-2, 2, 3) for _ in range(count)], [rng.uniform(PARAM_LO, PARAM_HI) for _ in range(count)]


def test_param_box_shapes_are_consistent():
    assert PARAM_LO.shape == (N_PARAMS,)
    assert PARAM_HI.shape == (N_PARAMS,)
    assert np.all(PARAM_HI > PARAM_LO)


def test_generators_are_proper_rotations():
    for M in (C4Z, SIGMA3):
        assert np.allclose(M @ M.T, np.eye(3), atol=TOL)
        assert np.linalg.det(M) == pytest.approx(1.0, abs=1e-12)


def test_generated_group_has_order_24():
    assert len(_close_group([C4Z, SIGMA3])) == 24


def test_flow_is_O_equivariant_under_full_group():
    G = _close_group([C4Z, SIGMA3])
    rng = np.random.default_rng(20260614)
    states, params = _states_params(rng, 60)
    for X, p in zip(states, params):
        FX = velocity(X, p)
        for g in G:
            assert np.allclose(velocity(g @ X, p), g @ FX, atol=TOL, rtol=0)


def test_flow_is_NOT_inversion_equivariant():
    """The cross term is even under inversion, so O_h is broken -> proper O (chiral)."""
    rng = np.random.default_rng(11)
    states, params = _states_params(rng, 50)
    violations = sum(
        not np.allclose(velocity(INV @ X, p), INV @ velocity(X, p), atol=1e-9)
        for X, p in zip(states, params)
    )
    assert violations == len(states)


def test_flow_is_NOT_SO3_equivariant():
    """The anisotropic (x^3,y^3,z^3) term reduces SO(3) to O -- random rotations break it."""
    rng = np.random.default_rng(22)
    states, params = _states_params(rng, 40)
    violations = 0
    for X, p in zip(states, params):
        g = _rand_rotation(rng)
        if not np.allclose(velocity(g @ X, p), g @ velocity(X, p), atol=1e-7):
            violations += 1
    assert violations == len(states)


def test_nonlinear_terms_are_load_bearing():
    """a = b = 0 -> only the radial scalar term, which is fully SO(3)-equivariant."""
    from atlas.family_o import param_names

    names = param_names()
    ai, bi = names.index("a"), names.index("b")
    rng = np.random.default_rng(33)
    states, params = _states_params(rng, 40)
    for X, p in zip(states, params):
        p = np.array(p, dtype=float)
        g = _rand_rotation(rng)
        # nonlinear terms present -> SO(3) broken
        assert not np.allclose(velocity(g @ X, p), g @ velocity(X, p), atol=1e-7)
        # remove them -> SO(3) (hence O, O_h) restored
        p[ai] = 0.0
        p[bi] = 0.0
        assert np.allclose(velocity(g @ X, p), g @ velocity(X, p), atol=1e-10)
        assert np.allclose(velocity(INV @ X, p), INV @ velocity(X, p), atol=1e-10)
