"""Core definition of the Mobula attractor.

The Mobula system is the first *improper*-symmetry member of the program. Where
Naiad (C2), Aurelia (C3), and Cassiopea (C4) are equivariant under pure
rotations, Mobula is equivariant under the order-4 rotoreflection group S4
(Schoenflies notation), generated by

    sigma: (w, z) -> (i*w, -z)            quarter-turn PLUS vertical flip

with w = x + i*y. The attractor is its own upside-down quarter-turn: rotate it
90 degrees about the vertical axis AND flip it top-to-bottom and it maps onto
itself -- but it is NOT symmetric under the quarter-turn alone or the flip
alone. sigma^2 sends (w, z) -> (-w, z) (the half-turn C2), so the symmetry group
is {I, sigma, sigma^2, sigma^3}, cyclic of order 4, equal to S4.

A devil ray (genus Mobula) breaches and somersaults clear out of the water --
flipping as it spins -- which is exactly this rotation-plus-reflection; seen
from the side the attractor is a broad-winged ray with layered veils, and from
above a four-armed pinwheel.

The complex form (the candidate family of docs/SYMMETRY_PROGRAM.md, with every
term verified S4-equivariant in tests/test_s4_equivariance.py):

    dw/dt = (alpha*z^2 - beta + i*omega) w + gamma*conj(w)^3 + delta*z*conj(w)
    dz/dt = nu*z - z^3 - lam*z*|w|^2 + eps*Im(w^2)

In real coordinates, with conj(w)^3 = (x^3 - 3xy^2) - i(3x^2 y - y^3) and
Im(w^2) = 2xy:

    dx/dt = (alpha*z^2 - beta + delta*z) x - omega*y + gamma*(x^3 - 3xy^2)
    dy/dt = (alpha*z^2 - beta - delta*z) y + omega*x + gamma*(y^3 - 3x^2 y)
    dz/dt = nu*z - z^3 - lam*z*(x^2 + y^2) + 2*eps*x*y

The signature term delta*z*conj(w) appears as a z-modulated anisotropic stretch
(+delta*z on the x-rate, -delta*z on the y-rate) whose sign reverses with z --
the mechanism that ties the quarter-turn to the flip. Because S4 forbids a
constant in dz/dt, the on-axis equilibria are the symmetric triple z(nu - z^2)=0,
i.e. (0,0,0) and the sigma-conjugate pair (0,0,+-sqrt(nu)).

Canonical parameters: alpha = 1.41039, beta = 0.670108, omega = 2.426585,
                      gamma = 0.3, delta = 0.553378, nu = 3.3,
                      lam = 2.135518, eps = 1.215326.
"""

from __future__ import annotations

import numpy as np

# Canonical parameters of the Mobula attractor.
ALPHA, BETA, OMEGA, GAMMA, DELTA, NU, LAM, EPS = (
    1.41039, 0.670108, 2.426585, 0.3, 0.553378, 3.3, 2.135518, 1.215326,
)

DEFAULT_STATE = (0.3, 0.2, 0.1)


def velocity(state, alpha=ALPHA, beta=BETA, omega=OMEGA, gamma=GAMMA,
             delta=DELTA, nu=NU, lam=LAM, eps=EPS):
    """Right-hand side of the Mobula system at ``state = (x, y, z)``."""
    x, y, z = state
    az2b = alpha * z * z - beta
    return np.array(
        [
            (az2b + delta * z) * x - omega * y + gamma * (x**3 - 3 * x * y * y),
            (az2b - delta * z) * y + omega * x + gamma * (y**3 - 3 * x * x * y),
            nu * z - z**3 - lam * z * (x * x + y * y) + 2 * eps * x * y,
        ]
    )


def jacobian(state, alpha=ALPHA, beta=BETA, omega=OMEGA, gamma=GAMMA,
             delta=DELTA, nu=NU, lam=LAM, eps=EPS):
    """Jacobian matrix of the flow at ``state = (x, y, z)``."""
    x, y, z = state
    az2b = alpha * z * z - beta
    return np.array(
        [
            [az2b + delta * z + 3 * gamma * (x * x - y * y),
             -omega - 6 * gamma * x * y,
             (2 * alpha * z + delta) * x],
            [omega - 6 * gamma * x * y,
             az2b - delta * z + 3 * gamma * (y * y - x * x),
             (2 * alpha * z - delta) * y],
            [-2 * lam * z * x + 2 * eps * y,
             -2 * lam * z * y + 2 * eps * x,
             nu - 3 * z * z - lam * (x * x + y * y)],
        ]
    )


def divergence(state, alpha=ALPHA, beta=BETA, omega=OMEGA, gamma=GAMMA,
               delta=DELTA, nu=NU, lam=LAM, eps=EPS):
    """Trace of the Jacobian. The delta*z and cubic terms cancel pairwise."""
    x, y, z = state
    return 2 * (alpha * z * z - beta) + nu - 3 * z * z - lam * (x * x + y * y)


def rk4_step(state, dt, alpha=ALPHA, beta=BETA, omega=OMEGA, gamma=GAMMA,
             delta=DELTA, nu=NU, lam=LAM, eps=EPS):
    """One classical fourth-order Runge-Kutta step."""
    p = (alpha, beta, omega, gamma, delta, nu, lam, eps)
    k1 = velocity(state, *p)
    k2 = velocity(state + 0.5 * dt * k1, *p)
    k3 = velocity(state + 0.5 * dt * k2, *p)
    k4 = velocity(state + dt * k3, *p)
    return state + (dt / 6.0) * (k1 + 2 * k2 + 2 * k3 + k4)


def trajectory(n_steps=500_000, dt=0.004, transient=40_000, state0=DEFAULT_STATE,
               alpha=ALPHA, beta=BETA, omega=OMEGA, gamma=GAMMA,
               delta=DELTA, nu=NU, lam=LAM, eps=EPS):
    """Integrate the flow and return an ``(n_steps, 3)`` array on the attractor."""
    p = (alpha, beta, omega, gamma, delta, nu, lam, eps)
    s = np.asarray(state0, dtype=float)
    for _ in range(transient):
        s = rk4_step(s, dt, *p)
    pts = np.empty((n_steps, 3))
    for i in range(n_steps):
        s = rk4_step(s, dt, *p)
        pts[i] = s
    return pts
