"""The S4 rotoreflection-equivariant search family, evaluated in batches.

This is the first *improper*-symmetry member of the program. Where the
C_n family (atlas/family.py) is equivariant under pure rotations w -> e^{2pi i/n} w,
this family is equivariant under the order-4 rotoreflection group S4
(Schoenflies), generated by

    sigma: (w, z) -> (i*w, -z)            quarter-turn PLUS vertical flip

with w = x + i*y. The attractor is its own upside-down quarter-turn, but is
NOT symmetric under the quarter-turn alone or the flip alone. sigma^2 sends
(w, z) -> (-w, z), the half-turn C2, so the group {I, sigma, sigma^2, sigma^3}
is cyclic of order 4 and equals S4.

The equivariance conditions for dw/dt = f, dz/dt = h (since sigma is linear,
F(sigma . s) = sigma . F(s)):

    f(i*w, -i*conj(w), -z) = i * f(w, conj(w), z)
    h(i*w, -i*conj(w), -z) = -  h(w, conj(w), z)

The candidate family (8 dials) -- every term audited against those conditions
in tests/test_s4_equivariance.py:

    dw/dt = (alpha*z^2 - beta + i*omega) w + gamma*conj(w)^3 + delta*z*conj(w)
    dz/dt = nu*z - z^3 - lam*z*|w|^2 + eps*Im(w^2)

Two terms are the SIGNATURE of S4: delta*z*conj(w) in dw/dt and eps*Im(w^2) in
dz/dt. Each is allowed under S4 (odd under sigma) but FORBIDDEN under the pure
quarter-turn C4 (where the allowed scalars are C4-invariant, e.g. |w|^2, and
Im(w^2) is not). They are exactly what reduces the symmetry from C4 to S4:
setting delta = eps = 0 restores C4 (covered by the test). Note there is no
constant in dz/dt -- a constant is even under sigma and therefore forbidden.

The evaluator mirrors atlas/family.py: vectorized complex RK4 over a whole
batch, a two-orbit Benettin estimate of the largest Lyapunov exponent, and a
decimated orbit sample for fingerprinting.
"""

from __future__ import annotations

import numpy as np

# Parameter order: (alpha, beta, omega, gamma, delta, nu, lam, eps)
_PARAM_NAMES = ("alpha", "beta", "omega", "gamma", "delta", "nu", "lam", "eps")
PARAM_LO = np.array([0.3, -1.0, 0.8, 0.3, 0.3, -1.0, 0.5, 0.3])
PARAM_HI = np.array([2.5, 1.5, 4.0, 2.5, 2.5, 2.5, 3.0, 2.5])
N_PARAMS = 8

ESCAPE = 50.0


def param_names():
    """Names of the eight parameters, in the order PARAM_LO/PARAM_HI use."""
    return list(_PARAM_NAMES)


def sigma(w, z):
    """The S4 generator: quarter-turn plus vertical flip, (w, z) -> (i*w, -z)."""
    return 1j * w, -z


def velocity(w, z, p):
    """Right-hand side (dw/dt, dz/dt) at a single state (w complex, z real).

    ``p`` is a length-8 array-like in the order given by ``param_names()``.
    """
    al, be, om, ga, de, nu, lam, eps = (float(v) for v in p)
    wb = np.conj(w)
    dw = (al * z * z - be + 1j * om) * w + ga * wb**3 + de * z * wb
    w2_im = (w * w).imag
    mod2 = (w * wb).real
    dz = nu * z - z**3 - lam * z * mod2 + eps * w2_im
    return dw, dz


def _deriv(W, Z, p):
    al, be, om, ga, de, nu, lam, eps = p.T
    Wb = np.conj(W)
    dW = (al * Z * Z - be + 1j * om) * W + ga * Wb**3 + de * Z * Wb
    mod2 = W.real**2 + W.imag**2
    w2_im = 2.0 * W.real * W.imag
    dZ = nu * Z - Z**3 - lam * Z * mod2 + eps * w2_im
    return dW, dZ


def _rk4(W, Z, p, dt):
    k1w, k1z = _deriv(W, Z, p)
    k2w, k2z = _deriv(W + 0.5 * dt * k1w, Z + 0.5 * dt * k1z, p)
    k3w, k3z = _deriv(W + 0.5 * dt * k2w, Z + 0.5 * dt * k2z, p)
    k4w, k4z = _deriv(W + dt * k3w, Z + dt * k3z, p)
    return (
        W + dt / 6.0 * (k1w + 2 * k2w + 2 * k3w + k4w),
        Z + dt / 6.0 * (k1z + 2 * k2z + 2 * k3z + k4z),
    )


def evaluate_batch(
    params,
    dt=0.01,
    transient=8_000,
    lyap_steps=25_000,
    sample_steps=12_000,
    sample_every=8,
    seed=0,
):
    """Evaluate a (B, 8) batch of S4 parameter vectors.

    Returns dict with:
      lle     (B,) largest Lyapunov exponent (nan where dead)
      alive   (B,) bool: bounded and finite throughout
      points  (B, sample_steps // sample_every, 3) orbit samples (nan where dead)
    """
    p = np.asarray(params, dtype=float)
    B = p.shape[0]
    rng = np.random.default_rng(seed)

    W = (rng.uniform(-0.4, 0.4, B) + 1j * rng.uniform(-0.4, 0.4, B)) + (0.3 + 0.2j)
    Z = rng.uniform(-0.2, 0.4, B)
    alive = np.ones(B, dtype=bool)

    def cull():
        nonlocal alive
        bad = ~np.isfinite(Z) | (np.abs(Z) > ESCAPE) | ~np.isfinite(W) | (np.abs(W) > ESCAPE)
        alive &= ~bad
        W[bad] = 0.0
        Z[bad] = 0.0

    with np.errstate(all="ignore"):
        for i in range(transient):
            W, Z = _rk4(W, Z, p, dt)
            if i % 200 == 0:
                cull()
        cull()

        d0 = 1e-8
        Ws, Zs = W + d0, Z.copy()
        log_sum = np.zeros(B)
        for i in range(lyap_steps):
            W, Z = _rk4(W, Z, p, dt)
            Ws, Zs = _rk4(Ws, Zs, p, dt)
            dW = Ws - W
            dZ = Zs - Z
            d = np.sqrt(dW.real**2 + dW.imag**2 + dZ**2)
            d = np.where(d > 0, d, 1e-16)
            log_sum += np.log(d / d0)
            scale = d0 / d
            Ws = W + dW * scale
            Zs = Z + dZ * scale
            if i % 200 == 0:
                cull()
        cull()
        lle = np.where(alive, log_sum / (lyap_steps * dt), np.nan)

        n_keep = sample_steps // sample_every
        pts = np.full((B, n_keep, 3), np.nan)
        k = 0
        for i in range(sample_steps):
            W, Z = _rk4(W, Z, p, dt)
            if i % sample_every == 0:
                pts[:, k, 0] = W.real
                pts[:, k, 1] = W.imag
                pts[:, k, 2] = Z
                k += 1
            if i % 200 == 0:
                cull()
        cull()
        pts[~alive] = np.nan

    return {"lle": lle, "alive": alive, "points": pts}


def sample_params(B, rng):
    """Uniform random parameter vectors inside the search box."""
    return rng.uniform(PARAM_LO, PARAM_HI, size=(B, N_PARAMS))


def mutate_params(parent, rng, sigma_frac=0.08):
    """Gaussian mutation, clipped to the box; sigma_frac is a fraction of each range."""
    span = PARAM_HI - PARAM_LO
    child = parent + rng.normal(0, sigma_frac, size=parent.shape) * span
    return np.clip(child, PARAM_LO, PARAM_HI)
